### ISSUE TITLE
Change URL for "Problems Paying?" Button

### ISSUE THREAD

**Issue by eddiewillers** [anypay/merchant-app#19]
There is a small button that pops up on the payment screen after 60 seconds of a merchant awaiting a payment.

It says, "Having trouble paying?" at the top, and it shows a question mark speech bubble in the bottom right corner of the payment collection screen.

That URL currently links to https://anypayinc.com/pay

That's fine, except there is currently nothing at that URL. So either the URL has to be changed, or a web page needs to be added at that URL. Otherwise, when the user taps the button, their browser opens up and navigates to a dead page.

![image](https://user-images.githubusercontent.com/4019818/223001360-0adf773c-07cb-4c66-b4a2-bdbdfc43a29d.png)

![image](https://user-images.githubusercontent.com/4019818/223001468-aabac926-b51d-47f4-929d-eaf6eda71979.png)

**Comment by eddiewillers** [comment]
Hi @pshenmic -- 

I just looked at this website's code and discovered that there is already a valid URL that will work quite nicely!

It is https://anypayx.com/faqs

It is safe and ideal to change that button's link to that URL, please.

Thank you very much!

**Comment by pshenmic** [comment]
https://anypayx.com/faq is the valid url
